notifications:
  email: false

matrix:
    include:
      - os: linux
        dist: trusty
        sudo: required
        language: python
        python: "2.7"
        env: COVERALLS=1 BUILD_SUITESPARSE=1 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1
      - os: linux
        dist: trusty
        sudo: required
        language: python
        python: "3.5"
        env: BUILD_SUITESPARSE=1 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1
      - os: osx
        env: PYVERSION=2.7 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1 CVXOPT_BLAS_LIB_DIR=/usr/local/opt/openblas/lib CVXOPT_BLAS_LIB=openblas CVXOPT_LAPACK_LIB=openblas
        language: generic
      - os: osx
        env: PYVERSION=2.7 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1 CVXOPT_BLAS_LIB_DIR=/usr/local/opt/openblas/lib CVXOPT_BLAS_LIB=openblas CVXOPT_LAPACK_LIB=openblas
        language: generic
      - os: osx
        env: PYVERSION=3.5 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1 CVXOPT_BLAS_LIB_DIR=/usr/local/opt/openblas/lib CVXOPT_BLAS_LIB=openblas CVXOPT_LAPACK_LIB=openblas
        language: generic

before_install:
  - if [[ "$BUILD_SUITESPARSE" == "1" ]]; then wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.3.tar.gz; tar -xf SuiteSparse-4.5.3.tar.gz; export CVXOPT_SUITESPARSE_SRC_DIR=$(pwd)/SuiteSparse; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-dev libopenblas-dev libfftw3-dev libglpk-dev libdsdp-dev libgsl0-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install homebrew/science/openblas homebrew/science/suite-sparse homebrew/science/glpk dsdp gsl fftw; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYVERSION" == "2.7" ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYVERSION" == "3.5" ]]; then brew install python3; virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  - pip install coveralls nose
  - pip install git+https://github.com/cvxopt/cvxopt@dev

script:
  - python -c 'from cvxopt import blas,lapack,glpk,fftw,dsdp,gsl,cholmod,umfpack'
  - nosetests --with-coverage --cover-package=cvxopt

after_success:
  - if [ $COVERALLS ]; then coveralls; fi
