notifications:
  email: false

matrix:
    include:
      - os: linux
        dist: trusty
        sudo: required
        language: python
        python: "2.7"
        env: CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1
      - os: linux
        dist: trusty
        sudo: required
        language: python
        python: "3.5"
        env: CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1
      - os: osx
        osx_image: xcode8.0
        env: PYVERSION=2.7 CVXOPT_SUITESPARSE_EXT_LIB=0 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1 CVXOPT_BLAS_LIB_DIR=/usr/local/opt/openblas/lib CVXOPT_BLAS_LIB=openblas CVXOPT_LAPACK_LIB=openblas
        language: generic
      - os: osx
        osx_image: xcode8.0
        env: PYVERSION=2.7 CVXOPT_SUITESPARSE_EXT_LIB=1 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1 CVXOPT_BLAS_LIB_DIR=/usr/local/opt/openblas/lib CVXOPT_BLAS_LIB=openblas CVXOPT_LAPACK_LIB=openblas
        language: generic
      - os: osx
        osx_image: xcode8.0
        env: PYVERSION=3.5 CVXOPT_SUITESPARSE_EXT_LIB=1 CVXOPT_BUILD_GSL=1 CVXOPT_BUILD_DSDP=1 CVXOPT_BUILD_FFTW=1 CVXOPT_BUILD_GLPK=1 CVXOPT_BLAS_LIB_DIR=/usr/local/opt/openblas/lib CVXOPT_BLAS_LIB=openblas CVXOPT_LAPACK_LIB=openblas
        language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-dev libopenblas-dev liblapack-dev libsuitesparse-dev libfftw3-dev libglpk-dev libdsdp-dev libgsl0-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYVERSION" == "2.7" ]]; then brew install python homebrew/science/openblas homebrew/science/suite-sparse homebrew/science/glpk dsdp gsl fftw; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYVERSION" == "2.7" ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYVERSION" == "3.5" ]]; then brew install python3 homebrew/science/openblas homebrew/science/suite-sparse homebrew/science/glpk dsdp gsl fftw; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYVERSION" == "3.5" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then pip install coveralls; fi
  - pip install git+https://github.com/cvxopt/cvxopt@dev

script:
  - python -c 'from cvxopt import blas,lapack,glpk,fftw,dsdp,gsl,cholmod,umfpack'
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then nosetests --with-coverage --cover-package=cvxopt; else nosetests; fi
